### ISSUE TITLE
Compile-time checks not OK?

### ISSUE THREAD

**Issue by baentsch** [google/cpu_features#102]
Hi, when following [your readme](https://github.com/google/cpu_features#checking-compile-time-flags) my compiler complained and I can't disagree with it: Your code
```CPU_FEATURES_COMPILED_X86_AVX || features.avx;```
after CPP expands to
```defined(__AVX__) || features.avx;```
and that doesn't compile (or is there a trick to get the CPP-command `defined` to become executable?).

--> Wouldn't it be better to do something like this in `cpu_features_macros.h`:
```c
#ifdef (__AVX__)
#define CPU_FEATURES_COMPILED_X86_AVX 1
#else 
#define CPU_FEATURES_COMPILED_X86_AVX 0
#endif 
```
instead of the current
```c
#define CPU_FEATURES_COMPILED_X86_AVX defined(__AVX__)
```
to make your sample code work?

Or should one use your sample code in a specific / different way than by simply gcc-ing it?

**Comment by gchatelet** [comment]
Thx for letting me know @baentsch . This code makes no sense indeed, I don't know what happened.
I've a #103 pending to fix it.

**Comment by baentsch** [comment]
@gchatelet Thanks very much for the quick reaction! Could you possibly also amend your PR by fixing what I perceive to be a typo on "CPU_FEATURES_COMPILED_x86_AVX2" (to "CPU_FEATURES_COMPILED_X86_AVX2")? The lowercase "x" (different to the uppercase "X" in all other macros) caused me a few more grey hairs not seeing immediately why AVX2 was the only feature not properly working in our code -- and I guess that can easily happen to more users of this now working (and IMO useful) "compile-time feature-set check" capability of `cpu-features`. Thanks in advance!

**Comment by Mizux** [comment]
@googlebot I consent
