### ISSUE TITLE
CMake requires a CXX compiler

### ISSUE THREAD

**Issue by gadoofou87** [google/cpu_features#109]
but he's not needed at all. It may be worth replacing `project(CpuFeatures VERSION 0.1.0)` with `project(CpuFeatures VERSION 0.1.0 LANGUAGES C)` in CMakeLists.txt. What do you think?

**Comment by Mizux** [comment]
After a quick check CMake 3.0 `project()` supports `LANGUAGES`.  
see: https://cmake.org/cmake/help/v3.0/command/project.html
