### ISSUE TITLE
Detection of Zen2 microarch

### ISSUE THREAD

**Issue by fireice-uk** [google/cpu_features#116]
The project that I'm working on needs detection of Zen2 microarchitecture. 

Most notably, Zen/Zen+ hasn't got physical YMM registers (they are simulated in microcode), therefore when choosing between code written for 128-bit vectors and code for 256-bit vectors, the former option will will be faster on Zen+ while the latter on Zen2 even though both support AVX on paper.

Adding it doesn't look too hard. I'm happy to do it myself and PR you the changes if that's welcome. 

Perhaps adding differentiation of Bulldozer micro-architectures would be a good idea too?

**Comment by gchatelet** [comment]
We should definitely support all the microarchitectures from
https://en.wikichip.org/wiki/amd#Microarchitectures

And PR are more than welcome to support them !
