### ISSUE TITLE
AVX-512 FMA count detection

### ISSUE THREAD

**Issue by jeffhammond** [google/cpu_features#120]
Would you like, or would you accept, contribution that detects the number of AVX-512 FMAs in Intel processors?  This is important in math libraries because processors with 1 FMA often perform better using AVX2 (or AVX3-256) code paths because of the frequency issues discussed in https://github.com/google/cpu_features/issues/10.

I've already solved this problem in https://github.com/jeffhammond/vpu-count but would like to contribute to a more serious project that is addressing a range of use cases.  I'm willing to maintain support for future hardware as long as I am in a position to do so and will document the methods required to maintain it.

**Comment by gchatelet** [comment]
Yes ! I would be very interested in these ! Thank you for the offer.
