### ISSUE TITLE
Atom processor detected as X86_UNKNOWN

### ISSUE THREAD

**Issue by gchatelet** [google/cpu_features#140]
family: 6
model: 28
stepping: 2
Name: Intel(R) Atom(TM) CPU  230   @ 1.60GHz

**Comment by Mizux** [comment]
ref:
https://ark.intel.com/content/www/us/en/ark/products/35635/intel-atom-processor-230-512k-cache-1-60-ghz-533-mhz-fsb.html
and
https://en.wikichip.org/wiki/intel/atom/230#Documents

where did you get model and stepping ?

**Comment by gchatelet** [comment]
> ref:
> https://ark.intel.com/content/www/us/en/ark/products/35635/intel-atom-processor-230-512k-cache-1-60-ghz-533-mhz-fsb.html
> and
> https://en.wikichip.org/wiki/intel/atom/230#Documents
> 
> where did you get model and stepping ?

from `/proc/cpuinfo` it's an old box of mine :)
