### ISSUE TITLE
ECCN for cpu_features

### ISSUE THREAD

**Issue by shridhargowda100** [google/cpu_features#145]
Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for cpu_features if it applies. Can you please let me know the ECCN ?

**Comment by Mizux** [comment]
I'm not an expert, I think cpu_features is **NOT** on the Commerce Control List (CCL) so maybe, you could use `EAR99`, but you should ask to a lawyer instead. 

ref:
https://www.bis.doc.gov/index.php/licensing/commerce-control-list-classification/export-control-classification-number-eccn
https://www.bis.doc.gov/index.php/documents/regulations-docs/13-commerce-control-list-index/file
