### ISSUE TITLE
Building fails on Raspberry Pi OS when run with 64bit kernel since cpu_features mistakes the kernel's arch for userspace's

### ISSUE THREAD

**Issue by ThomasHabets** [google/cpu_features#148]
```
xxx@pi4:~/src/volk/cpu_features/build$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for getauxval
-- Looking for getauxval - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/src/volk/cpu_features/build
xxx@pi4:~/src/volk/cpu_features/build$ make
Scanning dependencies of target utils
[ 12%] Building C object CMakeFiles/utils.dir/src/filesystem.c.o
[ 25%] Building C object CMakeFiles/utils.dir/src/stack_line_reader.c.o
[ 37%] Building C object CMakeFiles/utils.dir/src/string_view.c.o
[ 37%] Built target utils
Scanning dependencies of target unix_based_hardware_detection
[ 50%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/hwcaps.c.o
[ 50%] Built target unix_based_hardware_detection
Scanning dependencies of target cpu_features
[ 62%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_aarch64.c.o
In file included from /home/xxx/src/volk/cpu_features/src/cpuinfo_aarch64.c:15:
/home/xxx/src/volk/cpu_features/include/cpuinfo_aarch64.h:153:2: error: #error "Including cpuinfo_aarch64.h from a non-aarch64 target."
 #error "Including cpuinfo_aarch64.h from a non-aarch64 target."
  ^~~~~
make[2]: *** [CMakeFiles/cpu_features.dir/build.make:63: CMakeFiles/cpu_features.dir/src/cpuinfo_aarch64.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/cpu_features.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
xxx@pi4:~/src/volk/cpu_features/build$ uname -a
Linux pi4 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux
xxx@@pi4:~/src/volk/cpu_features/build$ file /bin/ls
/bin/ls: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=67a394390830ea3ab4e83b5811c66fea9784ee69, stripped
```

So this is 64bit arm architecture with a 32bit userland. Default GCC target is correctly 32bit, since `__aarch64__` doesn't seem to be defined.

(again a problem that probably would have been avoided if people would just stop using cmake and use something working like autotools)

**Comment by Mizux** [comment]
So you bump into
https://github.com/google/cpu_features/blob/6d0767e0d9269919452dfa20a326cb4a6529171a/include/cpuinfo_aarch64.h#L152-L154
since `CPU_FEATURES_ARCH_AARCH64` is not defined which should be the case if passing there.
https://github.com/google/cpu_features/blob/3cc8f310d950b44cc6d2ead8057cf43330a726fd/include/cpu_features_macros.h#L42-L44

BUT I suppose CMake correctly figure out it is a aarch64 platform using
https://github.com/google/cpu_features/blob/3cc8f310d950b44cc6d2ead8057cf43330a726fd/CMakeLists.txt#L62-L63
and
https://github.com/google/cpu_features/blob/3cc8f310d950b44cc6d2ead8057cf43330a726fd/CMakeLists.txt#L79-L81

Did you try to force your borken 32bit using `-DCMAKE_SYSTEM_PROCESSOR=arm` ?
ref: https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html

**Comment by ThomasHabets** [comment]
@Mizux my install is not broken. It's not at all uncommon to have 64bit kernel with 32bit userland.

gcc clearly knows that it's building 32bit userland. I don't know what CMake is up to:

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) 
```

Thanks for the map into CMakeLists. No, `-DCMAKE_SYSTEM_PROCESSOR=arm` didn't work, CMake still thinks it's aarch64. Changing `cpu_features/CMakeLists.txt` to `set(PROCESSOR_IS_ARM TRUE)` instead of aarch64 did, though. Thanks.

So maybe fix your borken CMake? :-P

**Comment by ThomasHabets** [comment]
Hmm, actually now that I think of it I'm pretty sure this is just normal stable supported raspberry pi os, but with `arm_64bit=1` set in `/boot/config.txt` to enable a 64bit kernel.

**Comment by ThomasHabets** [comment]
Ah, confirmed. This is vanilla Raspberry pi OS, with the official 64bit kernel.

**Comment by mgrouch** [comment]
I've run into same issue

https://github.com/anbox/anbox/issues/1905

**Comment by Mizux** [comment]
Does someone could give use the value of `CMAKE_HOST_SYSTEM_PROCESSOR` ?
i.e. adding in a CMakeLists.txt:
```cmake
message(FATAL_ERROR "CMAKE_HOST_SYSTEM_PROCESSOR: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
```
ref: https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html

i.e. I'm curious to know if CMake can "find" the userland system target and not the "kernel" one

**Comment by ThomasHabets** [comment]
```
$ uname -a
Linux pi4 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux
$ file /bin/ls
/bin/ls: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=67a394390830ea3ab4e83b5811c66fea9784ee69, stripped

cmake ..

CMake Error at CMakeLists.txt:258 (message):
  CMAKE_HOST_SYSTEM_PROCESSOR: aarch64
```

**Comment by ThomasHabets** [comment]
[This question](https://stackoverflow.com/questions/11944060/how-to-detect-target-architecture-using-cmake) seems to be saying there's no good way, but there's a workaround.

**Comment by gchatelet** [comment]
Since userland is not the same as the kernel (ARM EABI5 vs aarch64) there is nothing cmake can do. In fact this is to be considered as a cross compilation, so you need to define a crosstool chain. See https://cmake.org/cmake/help/latest/variable/CMAKE_TOOLCHAIN_FILE.html

**Comment by ThomasHabets** [comment]
But **everything** else works with this kind of setup.

In my opinion it doesn't matter that cmake sucks, but you could take responsibility for the library building on perfectly normal systems. This isn't even historically any kind of odd case.

At the very least your cmake setup should allow me to override when cmake's autodetection is broken.
