### ISSUE TITLE
Why no "Features revealed from Linux" under x86?

### ISSUE THREAD

**Issue by Happy-Ferret** [google/cpu_features#15]
Without having taken more than a brief look at the repo, what's the reason for not exposing the likes of ``/proc/cpuinfo`` under x86? Is there a reason or will this be supported in the future?

**Comment by gchatelet** [comment]
x86 provides all the information you need via the `cpuid` instruction and it is quite fast (a few hundreds of cycles). Using `/proc/cpuinfo` requires to read the file system and parse text which is both more error prone and slower. This can be added for sure but is it worth it?

**Comment by Happy-Ferret** [comment]
Ah! Thanks. I didn't even see that line (not that it's an excuse, but I'm having some troubles with my right eye today. Urgh).

Yea. Definitely no point then.

**Comment by gchatelet** [comment]
Happy to help!

**Comment by Myriachan** [comment]
Whether SSE (XMM register saving) is supported by the OS is the one thing that x86 doesn't expose, unless the CPU also has AVX, via the XCR0 register.  Detecting this, if it's worth bothering, requires reading `/proc/cpuinfo` on Linux x86-32.  (x86-64's definition requires the OS to support XMM register saving, so x86-64 user-mode code can assume SSE and SSE2 support.)
