### ISSUE TITLE
cpuinfo_ppc.h includes internal header

### ISSUE THREAD

**Issue by zhsj** [google/cpu_features#151]
https://github.com/google/cpu_features/blob/e2f6dea65f05ab95ff61dda5443480a7a39781ee/include/cpuinfo_ppc.h#L20

However this internal file is not installed by cmake.

**Comment by Mizux** [comment]
to add here if I'm not wrong
https://github.com/google/cpu_features/blob/e2f6dea65f05ab95ff61dda5443480a7a39781ee/CMakeLists.txt#L86-L88
