### ISSUE TITLE
Fails on FreeBSD: error: "Unsupported fallback detection of SSE OS support."

### ISSUE THREAD

**Issue by yurivict** [google/cpu_features#158]
```
#error "Unsupported OS"
 ^
/wrkdirs/usr/ports/devel/volk/work/volk-2.5.0/cpu_features/src/cpuinfo_x86.c:1268:2: error: "Unsupported fallback detection of SSE OS support."
#error "Unsupported fallback detection of SSE OS support."
 ^
2 errors generated.
```

**Comment by Mizux** [comment]
https://github.com/google/cpu_features/blob/bc2846e78faeb26b8a46c17df369d4e5f1f9e2bb/src/cpuinfo_x86.c#L1230-L1274

@yurivict Do you know which functions/implementation we could use to support SSE detection on a FreeBSD OS ?

**Comment by Mizux** [comment]
First it means we must detect FreeBSD OS here
https://github.com/google/cpu_features/blob/3e8243b7d9951c078259c3186c039a6e8f036055/include/cpu_features_macros.h#L70-L85

**Comment by yurivict** [comment]
You can detect FreeBSD with
```
#if defined(__FreeBSD__)
#endif 
```
