### ISSUE TITLE
add Macintosh Operating System

### ISSUE THREAD

**Issue by jf17** [google/cpu_features#16]
add support Macintosh Operating System (x86 and POWER) .
thank you =)

**Comment by jeffhammond** [comment]
MacOS PowerPC support is obsolete.  Why would you want that?
* https://apple.stackexchange.com/questions/1308/whats-the-last-os-x-that-supported-power-pc
* https://en.wikipedia.org/wiki/MacOS#PowerPC%E2%80%93Intel_transition

**Comment by jf17** [comment]
PowerPC support is optional.

**Comment by gchatelet** [comment]
MacOS is already working it uses the Linux implementation.
I'll update the documentation to reflect this.

You can build the project and use the `list_cpu_features` program to check it's working properly.
