### ISSUE TITLE
Join to translate English into Indonesian

### ISSUE THREAD

**Issue by mohdhaekal** [google/cpu_features#17]
hello sir ...
 may i translate into indonesia.agar bahasa indonesia is easier to read ..... ?
thank you very much for your attention

**Comment by orwant** [comment]
Hi mohdhaekal, thanks for the offer but cpu_features will be changing frequently and we'd prefer that the documentation not get out of sync.

**Comment by dandv** [comment]
@mohdhaekal: translation may help in the short run, but not in the long run. It's much more useful to learn English. See https://blog.codinghorror.com/the-ugly-american-programmer/.
