### ISSUE TITLE
Build failing due to lack of googletest; used to be disabled by default

### ISSUE THREAD

**Issue by mldulaney** [google/cpu_features#175]
Per cmake/README.md:

  CMake default options for cpu_features is Release built type with tests
  disabled. To enable testing set cmake `BUILD_TESTING` variable to `ON`,
  [.travis.yml](../.travis.yml) and [appveyor.yml](../appveyor.yml) have up to
  date examples.

I would prefer if this was returned to disabled by default as per the documentation.

**Comment by Mizux** [comment]
Sorry for this behaviour change, we decided to simply use `include(CTest)` and rely on the default value provided by this CMake builtin module to follow the documentation...
ref: https://cmake.org/cmake/help/latest/module/CTest.html

note: You can still use `-DBUILD_TESTING=OFF` to disable it.

todo: Update the README.md accordingly

**Comment by gchatelet** [comment]
Documentation is now
