### ISSUE TITLE
CMake: Install Missing

### ISSUE THREAD

**Issue by ax3l** [google/cpu_features#18]
Hi and thank you for the great project!

Can you please add `install()` lines to your CMake code? This would allow setting `-DCMAKE_INSTALL_PREFIX` to the cmake call and installing the final library via `make install`.

Here is an example on how to install targets in modern CMake:
  - https://github.com/pngwriter/pngwriter/blob/0.7.0/CMakeLists.txt#L140-L162

If you want, you can also generate a little [`*Config.cmake`](https://github.com/pngwriter/pngwriter/blob/0.7.0/PNGwriterConfig.cmake.in) file on install which makes it easy to find the library in projects depending on it.

**Comment by gchatelet** [comment]
@Mizux do you mind taking this over?

**Comment by Mizux** [comment]
Hi, yes I can do it, just few question:
- Based on the current proect name, will `CpuFeatures::` is an acceptable CMake namespace ?
- We will also need target alias `CPUFeature::cpu_features` so we can use the same target name when using cpu_features as a CMake subproject or via find_package(CpuFeatures CONFIG)...
- prefer to use include(GNUInstallDir) to define destination
- Need to check/fix PUBLIC_HEADERS properties also so install exporte headers.

I'll have to update my test also cf https://github.com/Mizux/cmake-cpu_features/blob/master/CMakeLists.txt

**Comment by gchatelet** [comment]
`CpuFeatures::` namespace sounds good to me.
