### ISSUE TITLE
Small driver program to test from command line

### ISSUE THREAD

**Issue by vielmetti** [google/cpu_features#19]
It would be helpful in many ways to have a small driver program that would exercise the features of this library and would emit output on stdout after detecting all available features. This would allow for easier testing of the library on new platforms, as well as making it possible to integrate `cpu_features` into non-C99 applications.

**Comment by gchatelet** [comment]
It's already the case: https://github.com/google/cpu_features/blob/master/CMakeLists.txt#L63
Although this issue tells me this is not obvious... I'll update the README to point to the target.

**Comment by vielmetti** [comment]
got it! running on Cavium ThunderX (Packet Type 2A) arm64:

```
cmake# ./list_cpu_features 
arch            : aarch64
implementer     :  67 (0x43)
variant         :   1 (0x01)
part            : 161 (0xA1)
revision        :   1 (0x01)
flags           : aes, asimd, crc32, fp, pmull, sha1, sha2
```

I'll still need a secret decoder ring for arm64 parts, though.

**Comment by vielmetti** [comment]
By comparison `cat /proc/cpuinfo` gives me

```
processor       : 95
BogoMIPS        : 200.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x43
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0x0a1
CPU revision    : 1
```

for each of 96 cores

**Comment by vielmetti** [comment]
If I'm asking about the CLI, it would be super-handy to have a `-o json` flag so that output would be easy to parse.

**Comment by gchatelet** [comment]
@vielmetti Do you mind creating another issue to support a `--json` option?
I'll close this one with an update on the README.
Thank you!
