### ISSUE TITLE
vpclmulqdq should be pclmulqdq

### ISSUE THREAD

**Issue by Myriachan** [google/cpu_features#2]
vpclmulqdq should be pclmulqdq.  The "v" version of the instruction simply means to encode the instruction in AVX format instead of SSE format.

**Comment by Myriachan** [comment]
I made a mistake.  vpclmulqdq is now a future feature that is actually a vectorized multiply.  The code was correct before.
https://software.intel.com/sites/default/files/managed/c5/15/architecture-instruction-set-extensions-programming-reference.pdf

However, there is a separate pclmulqdq (old version) bit that should be added: leaf 1 ecx bit 1.

I am sorry about this; I didn't know about the newest information.

**Comment by gchatelet** [comment]
It's fine, it happens :) I should have double checked.
Do you mind opening another issue for the missing feature? I'll revert the commit. Thx!
