### ISSUE TITLE
testsuite fails because googletest renamed master branch into main for some reason

### ISSUE THREAD

**Issue by yurivict** [google/cpu_features#216]

**Comment by Mizux** [comment]
Hi,

which branch/tag did you use ?

on master it seems we are OK
https://github.com/google/cpu_features/blob/master/cmake/googletest.CMakeLists.txt.in

**Comment by yurivict** [comment]
0.6.0

**Comment by gchatelet** [comment]
The renaming away from `master` stems from community considerations. `master` is a loaded term that refers to slavery.
There is a wide effort to move away from it and use the `main` branch instead. Here are a few links:

 - https://developers.google.com/style/word-list#master
 - https://github.com/github/renaming
 - https://foundation.llvm.org/docs/branch-rename/

**Comment by yurivict** [comment]
Thanks.
