### ISSUE TITLE
missed X86 Intel Comet Lake detection

### ISSUE THREAD

**Issue by ajax16384** [google/cpu_features#248]
missed Comet Lake detection

cpuinfo_x86.h
````c
  INTEL_CML,           // COMET LAKE
````

- no stepping 12 case for U Comet Lake flavor
https://github.com/google/cpu_features/blob/db9ad9fc2ccfbbb1815c1459b2151d57b773ddd3/src/impl_x86__base_implementation.inl#L536
````c
          case 12:
            return INTEL_CML;  // https://en.wikichip.org/wiki/intel/microarchitectures/comet_lake
````

- no case CPUID(0x06, 0xA5) for S/H Comet Lake
````c
          case CPUID(0x06, 0xA5):
            return INTEL_CML;  // https://en.wikichip.org/wiki/intel/microarchitectures/comet_lake
````

**Comment by gchatelet** [comment]
@ajax16384 do you mind adding a test as well?
Something like https://github.com/google/cpu_features/commit/3c4801d12d9bec823d03a572f4f53cd42fa02b42#diff-35206f4b4b826d1011c7f40612491fcc1d480572cd4ea48e1bbd73049cf969a2

**Comment by ajax16384** [comment]
> @ajax16384 do you mind adding a test as well? Something like [3c4801d#diff-35206f4b4b826d1011c7f40612491fcc1d480572cd4ea48e1bbd73049cf969a2](https://github.com/google/cpu_features/commit/3c4801d12d9bec823d03a572f4f53cd42fa02b42#diff-35206f4b4b826d1011c7f40612491fcc1d480572cd4ea48e1bbd73049cf969a2)

ok
