### ISSUE TITLE
AVX_VNNI support?

### ISSUE THREAD

**Issue by amitdo** [google/cpu_features#263]
It seem you don't support it.

Alder Lake has `AVX_VNNI`. The next desktop and server CPUs from Intel will have it.

**Comment by amitdo** [comment]
https://github.com/tensorflow/tensorflow/blob/18d203b1ef84b1/tensorflow/core/platform/cpu_info.cc#L226

**Comment by toor1245** [comment]
@amitdo, thanks for the issue. According to documentation, [intel-architecture-instruction-set-extensions-programming-reference 27 page](https://www.intel.com/content/dam/develop/external/us/en/documents/architecture-instruction-set-extensions-programming-reference.pdf) we can add it
![image](https://user-images.githubusercontent.com/43444946/182922341-b30f4449-b38f-4354-94e8-21acd6163c1e.png)

To add it we need to  `features->avx_vnni = IsBitSet(leaf_7_1.eax, 4);`

**Comment by Mizux** [comment]
closed by #264

**Comment by amitdo** [comment]
@toor1245, thanks.
