### ISSUE TITLE
Power Architecture support

### ISSUE THREAD

**Issue by ajdlinux** [google/cpu_features#28]
Opening this to track support for Power Architecture.

@grooverdan and I are currently sorting out our IBM approvals to work on this.

**Comment by ajdlinux** [comment]
internal approvals have happened, @RashmicaG is interested in taking a look at this too

**Comment by gchatelet** [comment]
Awesome, let me know if I can help.

It would have been nice to have a cleaner structure for the code (see https://github.com/google/cpu_features/issues/3) but I tried a few ones and it didn't converge to something clearer. I'll have a bit more time in the upcoming days: I'll give it another try.

**Comment by jan-wassenberg** [comment]
FYI: I've seen compilers turn simple for-loops into memcpy. If used within the library (not just test), we'd need to be careful to prevent that.

**Comment by gchatelet** [comment]
Closing this issue now. Thx for your contribution @RashmicaG !
