### ISSUE TITLE
I was aske to report this ecause it might aso be a security issue. BREW SHA256 error

### ISSUE THREAD

**Issue by John-Telek** [google/cpu_features#307]
Brew is broken.
Looks like the checksum for the v0.8.0 archive at https://github.com/google/cpu_features.git changed.

Could you report this to https://github.com/google/cpu_features.git? This is a potential security issue, so we want to check that the change is checksum was intentional before proceeding. This is often caused by tags being replaced for innocuous reasons, but we should make sure before assuming this.

==> Fetching cpu_features
==> Downloading https://github.com/google/cpu_features/archive/v0.8.0.tar.gz
Already downloaded: /Users/johntelek/Library/Caches/Homebrew/downloads/987ce5a9627ffb58af330dbb6bbfeab569d17a883a9fcb9d061061a40233aa64--cpu_features-0.8.0.tar.gz
Error: volk: SHA256 mismatch <----------------------------------ERROR-------------------------------------
Expected: a3fc6a08ebbf40c538456d6a20ab294658bcebc8d0918457f33cb86f868f16a2
Actual: 7021729f2db97aa34f218d12727314f23e8b11eaa2d5a907e8426bcb41d7eaac
File: /Users/johntelek/Library/Caches/Homebrew/downloads/987ce5a9627ffb58af330dbb6bbfeab569d17a883a9fcb9d061061a40233aa64--cpu_features-0.8.0.tar.gz
To retry an incomplete download, remove the file above.
johntelek@Johns-Mac-mini ~ %

Regards,
  John.

**Comment by toor1245** [comment]
ping @gchatelet, @Mizux

**Comment by gchatelet** [comment]
Yes the change was intentional.
I initially created `v8.0.0` and pushed the tag upstream but without pushing the associated commit on `main`.
Meanwhile a change has been accepted on `main` making the reconciliation impossible.

I've deleted the tag and recreated it so everything is sane again.

**Comment by gchatelet** [comment]
Thx for bringing this up @John-Telek and sorry for the inconvenience. I should have created a v8.0.1 instead...

**Comment by VincentVolmer** [comment]
Hello,

I also experiencing the same. Is there a solution for this already?

`Error: volk: SHA256 mismatch
Expected: a3fc6a08ebbf40c538456d6a20ab294658bcebc8d0918457f33cb86f868f16a2
  Actual: 7021729f2db97aa34f218d12727314f23e8b11eaa2d5a907e8426bcb41d7eaac
    File: /Users/vincentvolmer/Library/Caches/Homebrew/downloads/987ce5a9627ffb58af330dbb6bbfeab569d17a883a9fcb9d061061a40233aa64--cpu_features-0.8.0.tar.gz
`

**Comment by Mizux** [comment]
We should send a PR/patch to homebrew to fix the SHA256 there !
https://github.com/Homebrew/homebrew-core/blob/master/Formula/cpu_features.rb
