### ISSUE TITLE
clang-format check is broken

### ISSUE THREAD

**Issue by tamaszarm** [google/cpu_features#311]
In the "Check current commit" step, git fails to find the repository. For an example, see this job: https://github.com/google/cpu_features/actions/runs/5221342145/jobs/9425484204?pr=310

**Comment by Mizux** [comment]
Good Catch ! Thanks for the report !

**Comment by gchatelet** [comment]
@Mizux can we fix this one before I release v0.9.0? If not I'll just remove it from the milestone.
