### ISSUE TITLE
Documentation error or CMake error when linking

### ISSUE THREAD

**Issue by ashley-b** [google/cpu_features#333]
When trying to link to this library the docs say the target name should be CpuFeature::cpu_features
https://github.com/google/cpu_features/tree/main/cmake
But it is exported as CpuFeatures https://github.com/google/cpu_features/blob/b960bcf0f5bca0f05d6ae7f89ddd8ff42893df0f/CMakeLists.txt#L280
Internal it is correct https://github.com/google/cpu_features/blob/b960bcf0f5bca0f05d6ae7f89ddd8ff42893df0f/CMakeLists.txt#L183

So am unsure if this is a bug or a documentation error

**Comment by Mizux** [comment]
Typo issue ! Good catch I would go with the 's' and change the ALIAS so for installed cpu_features it won't change but for using add_subdirectory()/FetchContent() you'll have to change if using the alias...

**Comment by gchatelet** [comment]
Thx for noticing @ashley-b !
