### ISSUE TITLE
Overwriting windows syscalls

### ISSUE THREAD

**Issue by Leandros** [google/cpu_features#34]
Windows, the Win32 API in specific, has a function called `ReadFile`, `OpenFile` and `CloseFile`. You define all three in filesystem.c, non-namespaced, and therefore overriding the Win32 syscalls for everybody who links with your library. This is a huge oversight and cost me a couple of hours of trying to figure out why my programs all start to crash when reading files out of a sudden.

https://github.com/google/cpu_features/blob/7eca4a7a399e8c96a6dacf09c0c59d558c62f45a/src/filesystem.c#L24-L30

**Comment by gchatelet** [comment]
Hi @Leandros 

Thx a lot for reporting this: I wasn't aware obviously.
Let's move the conversation on PR https://github.com/google/cpu_features/pull/35
