### ISSUE TITLE
SSSE3, SSE4.1, SSE4.2 not detected on non-AVX CPUs

### ISSUE THREAD

**Issue by Myriachan** [google/cpu_features#4]
ParseCpuId is coded to require the XMM XCR0 bit in order to recognize SSSE3, SSE4.1, and SSE4.2, but this is not the right way to detect it.  Machines without AVX will not have XCR0 at all, and will fail this check.

In the absence of XCR0, on x86-32, the proper way to detect SSE is to ask the operating system.  (On x86-64, just assume yes.)  In Windows, that's IsProcessorFeaturePresent(PF_XMMI_INSTRUCTIONS_AVAILABLE).  In Linux, unfortunately, it's parsing /proc/cpuinfo.  In macOS and iOS (simulator), it's sysctlbyname on hw.optional.sse, though you could also just assume yes.

Something could be said that the number of x86 machines without SSE in the CPU and OS is about zero now--it depends on how far back you want your library to support.

**Comment by aprelev** [comment]
Ping.

**Comment by WilliamTambellini** [comment]
I confirm the bug:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 44
model name      : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
stepping        : 2
cpu MHz         : 2660.000
cache size      : 256 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pni ssse3 cx16 sse4_1 sse4_2 popcnt aes hypervisor lahf_lm ida arat dtherm
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual

and list_cpu_features does nt report much: 

$ list_cpu_features
arch            : x86
brand           : Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
family          :   6 (0x06)
model           :  44 (0x2C)
stepping        :   2 (0x02)
uarch           : INTEL_WSM
flags           : aes,cx16,popcnt

**Comment by WilliamTambellini** [comment]
Some have a point here : even if indeed non avx cpus are rare, "strange" CPUs could be often met when the user is using virtualized cpus (aka VM, even perhaps docker slaves) where the cpus features are not always preserved from host to vm.

**Comment by wmark** [comment]
Non-AVX are not negligible indeed, imho. The entire class of Atom notebooks, likely with low memory, don't have AVX; and run a 32 bit operating system.

**Comment by gchatelet** [comment]
@Myriachan how would you detect `ssse3`, `sse4.1` and `sse4.2` on Windows for pre AVX cpus?
`IsProcessorFeaturePresent` seems to stop at `sse3`.

**Comment by wmark** [comment]
FYI, x86-32–only cpus with `sse4`* exist, for example Intel's *Quark* series (cut from *Silvermont*).
