### ISSUE TITLE
Unable to build this on macOS

### ISSUE THREAD

**Issue by abhi18av** [google/cpu_features#45]
@gchatelet , I ran into an error while running this command on the `macOS` system 

```

Abhinavs-MacBook-Pro:cpu_features eklavya$ cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -H. -Bcmake_build
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/eklavya/projects/code/c-shared-lab/cpu_features/cmake_build


Abhinavs-MacBook-Pro:cpu_features eklavya$ cd cmake_build/


Abhinavs-MacBook-Pro:cmake_build eklavya$ make 
Scanning dependencies of target cpu_features
[  6%] Building C object CMakeFiles/cpu_features.dir/src/linux_features_aggregator.c.o
[ 13%] Building C object CMakeFiles/cpu_features.dir/src/cpuid_x86_clang_gcc.c.o
[ 20%] Building C object CMakeFiles/cpu_features.dir/src/cpuid_x86_msvc.c.o
[ 26%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_aarch64.c.o
[ 33%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_arm.c.o
[ 40%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_mips.c.o
[ 46%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_ppc.c.o
[ 53%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_x86.c.o
[ 60%] Building C object CMakeFiles/cpu_features.dir/src/filesystem.c.o
[ 66%] Building C object CMakeFiles/cpu_features.dir/src/hwcaps.c.o
[ 73%] Building C object CMakeFiles/cpu_features.dir/src/stack_line_reader.c.o
[ 80%] Building C object CMakeFiles/cpu_features.dir/src/string_view.c.o
[ 86%] Linking C shared library libcpu_features.dylib
Undefined symbols for architecture x86_64:
  "_CpuFeatures_GetPlatformType", referenced from:
      _GetPPCPlatformStrings in cpuinfo_ppc.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libcpu_features.dylib] Error 1
make[1]: *** [CMakeFiles/cpu_features.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Mizux** [comment]
here 
https://github.com/google/cpu_features/blob/78635347dbb03a2d3cc8543308e2bede4d6c12f9/include/cpu_features_macros.h#L52-L62

I would add
```c
 #if defined(__APPLE__) 
 #define CPU_FEATURES_OS_APPLE 
 #endif 
```
or
```c
 #if defined(__OSX__) 
 #define CPU_FEATURES_OS_OSX
 #endif 
```

then adapt accordingly
https://github.com/google/cpu_features/blob/master/src/hwcaps.c#L38-L45

**Comment by gchatelet** [comment]
According to https://sourceforge.net/p/predef/wiki/OperatingSystems/ we should test for `__APPLE__ && __MACH__`

**Comment by Mizux** [comment]
Be careful these are both defined also on iOS too
src: http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#OSXiOSandDarwin

**Comment by sl1200mk2** [comment]
Hi,
so how to get cpu_features to compile on macOS?
I'm facing the same issue as Mizux...

thank you
++

**Comment by Mizux** [comment]
@abhi18av @sl1200mk2 
It seems you are using the `/Library/Developer/CommandLineTools/usr/bin/cc` which is the wrong active developer directory.
You should use instead this one `/Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/gcc`.

To change please run `xcode-select --install`

@gchatelet Travis-CI Mac workers seems "correctly" configured in this regard...
see: https://travis-ci.org/google/cpu_features/jobs/427262835#L140-L144

**Comment by Mizux** [comment]
@gchatelet I still think there is a bug since `cpuinfo_ppc.c` call `CpuFeatures_GetPlatformType();`
https://github.com/google/cpu_features/blob/78635347dbb03a2d3cc8543308e2bede4d6c12f9/src/cpuinfo_ppc.c#L167-L173

But `CpuFeatures_GetPlatformType()` is undefined for `!HWCAPS_SUPPORTED`:
https://github.com/google/cpu_features/blob/78635347dbb03a2d3cc8543308e2bede4d6c12f9/src/hwcaps.c#L164-L187

I think, we should add this to the `#else`
```c
PlatformType kEmptyPlatformType;
PlatformType CpuFeatures_GetPlatformType(void) {
  return kEmptyPlatformType;
}
```

**Comment by jculpon** [comment]
Not @google but I'd like to confirm that a clean CMake on macOS 10.14.2 with a GNU-based toolchain is building successfully, but I have not been able to get tests passing with llvm this morning. This may be unrelated to the issues that @gchatelet / @Mizux are having.

**Comment by gchatelet** [comment]
@Mizux the build is now fixed. I'm closing the issue.
