### ISSUE TITLE
New tag request

### ISSUE THREAD

**Issue by WilliamTambellini** [google/cpu_features#64]
0.2 tag is already several months old.
Would you now be open to create a new tag (0.3.0 or whatever) ?
Kind

**Comment by gchatelet** [comment]
Yes definitely, and especially with the recent addition of `ndk_compat` #47 
I'm waiting a bit for some Android Teams (ping @roland-levillain ) to check that the build is working correctly before doing the actual tagging.

**Comment by WilliamTambellini** [comment]
Cool. Could you also wait for the centos6 support PR ?

**Comment by gchatelet** [comment]
Yep SGTM.

**Comment by gchatelet** [comment]
Integration from Android Team takes more time than I thought, I'll tag master with 0.3 now and we can add another tag later if needed.

**Comment by gchatelet** [comment]
Done https://github.com/google/cpu_features/tree/v0.3.0

**Comment by aregm** [comment]
@gchatelet Thanks

**Comment by anton-malakhov** [comment]
@gchatelet Thanks! It still needs your attention as it is not marked as the latest release (https://github.com/google/cpu_features/releases/latest).
Also, I'm happy to announce [conda-forge feedstock](https://github.com/conda-forge/cpu_features-feedstock) for this library, so please don't forget to regularly mark stable releases. If you want to be listed as maintainer for the feedstock, please open PR adding your name in the [list](https://github.com/conda-forge/cpu_features-feedstock/blob/master/recipe/meta.yaml#L45).

**Comment by gchatelet** [comment]
Thx @anton-malakhov! I just released v0.3.0.
