### ISSUE TITLE
Link failure under centos 6 for the shared lib

### ISSUE THREAD

**Issue by WilliamTambellini** [google/cpu_features#65]
When trying to build with -DBUILD_SHARED_LIBS=ON : 
...
[ 77%] Linking C shared library libcpu_features.so
cmake-3.13.3/bin/cmake -E cmake_link_script CMakeFiles/cpu_features.dir/link.txt --verbose=1
gcc-6.1.0/bin/gcc -fPIC -O3 -DNDEBUG  -shared -Wl,-soname,libcpu_features.so -o libcpu_features.so CMakeFiles/cpu_features.dir/src/cpuinfo_x86.c.o CMakeFiles/utils.dir/src/filesystem.c.o CMakeFiles/utils.dir/src/stack_line_reader.c.o CMakeFiles/utils.dir/src/string_view.c.o -ldl 
/usr/bin/ld: CMakeFiles/utils.dir/src/string_view.c.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
CMakeFiles/utils.dir/src/string_view.c.o: could not read symbols: Bad value

The static lib builds ok, so not a blocking bug (for me) but still.

**Comment by gchatelet** [comment]
fixed by #66
