### ISSUE TITLE
Missing ARMv7 define

### ISSUE THREAD

**Issue by noloader** [google/cpu_features#71]
Thanks for the `cpu_features` library.

It looks like the library is missing a define for ARMv7. ARMv7 is important for some hand tuned algorithms. For example, one might bundle [Andy Polyakov's Cryptogams](https://www.openssl.org/~appro/cryptogams/) [AES](https://wiki.openssl.org/index.php/Cryptogams_AES) and [SHA](https://wiki.openssl.org/index.php/Cryptogams_SHA) algorithms, and make the baseline ARMv7 with `-march=armv7-a`. 

There are several reasons to make ARMv7 the baseline. ARMv7 is mostly the *de facto* standard nowadays, so using ARMv7 addresses the common case out of the box. ARMv7 ISA also enjoys a performance boost over older ISAs, and provides additional loads and stores not available in ARMv6 and below. However, ARMv5 and ARMv6 will show up on occasion, like old dev-boards and iPads, so a fallback is needed on occasion.

At runtime, user code may do something like the following:

```c
if (HasARMv7()) {
    CRYPTOGAMS_aes_encrypt(data, blocks, subkeys);
} else {
    CXX_aes_encrypt(data, blocks, subkeys);
}
```

We can't really use `ARM_NEON` as a proxy for ARMv7 because some ARMv6 devices have NEON. And some ARMv7 dev-boards lack NEON.

-----

It looks like Mozilla synthesises it from `/proc/cpuinfo` on Linux; see [Changeset 522951ff7046](https://hg.mozilla.org/releases/mozilla-aurora/rev/522951ff7046fd2bdf3916c973fbfde27be0af31). Crypto++ library utilizes a [`SIGILL` probe using `movw` and `movt`](https://github.com/weidai11/cryptopp/blob/master/neon_simd.cpp#L88) because `getauxval` does not provide a define (`movw` and `movt` are part of ARMv7 ISA):

```c
int a;
asm volatile("movw %0,%1 \n"
             "movt %0,%1 \n"
             : "=r"(a) : "i"(0x1234));

hasARMv7 = (a == 0x12341234);
```

Unfortunately, `SIGILL` probes have several of shortcomings. First, they are expensive when compared to `getauxval` and friends. Second, they only work with the GNU Assembler (GAS) or compatible assemblers. Third, they trash a program on Apple platforms. Apple does not restore the context properly when a `longjmp` is taken, so they can't be used on iPhones and iPads.

**Comment by gchatelet** [comment]
A gentle ping @noloader
