### ISSUE TITLE
Consider adding cpu_features to vcpkg

### ISSUE THREAD

**Issue by tlemo** [google/cpu_features#82]
Just an idea, adding cpu_features would be a great addition to to https://github.com/microsoft/vcpkg

**Comment by gchatelet** [comment]
I'm not familiar with Microsoft's `vcpkg` but contributions are welcome.

**Comment by tlemo** [comment]
No promises, but I might give it a try if I get a chance (I don't have experience with adding packages to vcpkg either)

For reference, these seem to be the basic instructions: https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md

**Comment by tlemo** [comment]
@mluparu, does the vcpkg team take requests to add new packages?

**Comment by mluparu** [comment]
Yes, of course. Start by submitting a new port requests here: https://github.com/microsoft/vcpkg/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22new+port+request+-+consider+making+a+PR%21%22+ 

You can also consider submitting a PR for the port directly to https://github.com/microsoft/vcpkg. This can speed up things significantly

**Comment by Mizux** [comment]
FYI it seems the 0.4.1 make its way into vcpkg: https://github.com/microsoft/vcpkg/tree/master/ports/cpu-features
