### ISSUE TITLE
no member named 'vfpv' in 'ArmFeatures' when compiling ndk_compat for arm

### ISSUE THREAD

**Issue by robertarnesson** [google/cpu_features#96]
Compiling ndk_compat for Android arm devices results in the error below:

`/build/src/ndk_compat/cpu-features.c:118:21: error: no member named 'vfpv' in 'ArmFeatures'
  if (info.features.vfpv) g_cpuFeatures |= ANDROID_CPU_ARM_FEATURE_VFPv2;
      ~~~~~~~~~~~~~ ^
1 error generated.`

..and sure enough looking in include/cpuinfo_arm.h there is no vfpv property. Looking through the file history it seems there never was. I'm scratching my head here, am I doing something wrong or is this a bug that has been there forever?

Commenting out line 118 in ndk_compat/cpu-features.c solves the issue

**Comment by gchatelet** [comment]
Thx it's a typo, it should have been `vfp` ([code](https://github.com/google/cpu_features/blob/d395dfa026d3c1177bb0e27ff3d1c95d04f42382/include/cpuinfo_arm.h#L24)).
