### ISSUE TITLE
cpu microarchitecture is not correct

### ISSUE THREAD

**Issue by tkorays** [google/cpu_features#97]
CPU-Z shows that CPU's code name is `Coffe Lake`, but this code's output is `Kaby Lake`.

**Comment by gchatelet** [comment]
Can you give me the output of `list_cpu_features --json` ?

**Comment by tkorays** [comment]
```
{"arch":"x86","brand":"Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz","family":6,"model":158,"stepping":10,"uarch":"INTEL_KBL","flags":[...]}
```
The wikipedia shows that The coffee lake's cpuid code(EAX) is 0x0906EA or 0x0906EB. 

I think CannonLake, WhiskeyLake, IceLake,  CometLake may get wrong results.
